services:
  frontend:
    volumes:
      - /app/node_modules
      - ./frontend:/app
  
  question:
    command: npm run dev
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./services/question:/app

  question-db:
    ports:
      - 27017:27017

  user:
    command: npm run dev
    ports:
      - 8082:8082
    volumes:
      - /app/node_modules
      - ./services/user:/app
  
  user-db:
    ports:
      - 27018:27017

  match:
    command: npm run dev
    ports:
      - 8083:8083
    volumes:
      - /app/node_modules
      - ./services/match:/app
  
  match-db:
    ports:
      - 27019:27017
  
  collaboration:
    command: npm run dev
    ports:
      - 8084:8084
    volumes:
      - /app/node_modules
      - ./services/collaboration:/app
    
  collaboration-db:
    ports:
      - 27020:27017
  
  collaboration-db:
    ports:
      - 27020:27017
  
  history:
    command: npm run dev
    ports:
      - 8086:8086
    volumes:
      - /app/node_modules
      - ./services/history:/app
  
  history-db:
    ports:
      - 27021:27017
  
  broker:
    ports:
      - 5672:5672

  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8080
    restart: always
