services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    restart: always
  
  question:
    container_name: question
    image: question
    build:
      context: services/question
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    environment:
      DB_URI: ${QUESTION_DB_URI}
      DB_USERNAME: ${QUESTION_DB_USERNAME}
      DB_PASSWORD: ${QUESTION_DB_PASSWORD}
    networks:
      - question-db-network
    restart: always

  user:
    container_name: user
    image: user
    build:
      context: services/user
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      USER_SERVICE_CLOUD_URI: ${USER_SERVICE_CLOUD_URI}
      USER_SERVICE_LOCAL_URI: ${USER_SERVICE_LOCAL_URI}
      ENV: ${ENV}
      JWT_SECRET: ${JWT_SECRET}
    restart: always

volumes:
  question-db:

networks:
  question-db-network:
    driver: bridge