services:
  frontend:
    container_name: frontend
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    volumes:
      - /app/node_modules
      - ./frontend:/app
    networks:
      - question-network
  
  question:
    container_name: question
    image: question
    build:
      context: services/question
      dockerfile: Dockerfile
    environment:
      MONGODB_USERNAME: ${QUESTION_DB_USERNAME}
      MONGODB_PASSWORD: ${QUESTION_DB_PASSWORD}
    ports:
      - 8081:8081
    volumes:
      - /app/node_modules
      - ./services/question:/app
    networks:
      - question-network
      - question-db-network

  question-db:
    container_name: question-db
    image: mongo:7.0.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${QUESTION_DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${QUESTION_DB_PASSWORD}
    volumes:
      - question-db:/data/db
    networks:
      - question-db-network

volumes:
  question-db:

networks:
  question-network:
    driver: bridge
  question-db-network:
    driver: bridge